# Generated by Django 2.0.7 on 2018-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('USN', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMAlE')], max_length=5)),
            ],
        ),
    ]
