# Generated by Django 2.0.7 on 2018-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_iamarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffId', models.IntegerField()),
                ('staff_name', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
