# Generated by Django 2.0.7 on 2018-10-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181003_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iamarks',
            name='semIA',
        ),
        migrations.AddField(
            model_name='iamarks',
            name='SEM',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
