# Generated by Django 2.0.7 on 2018-10-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20181003_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='owner',
        ),
        migrations.AddField(
            model_name='staffsubjects',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
