# Generated by Django 2.0.7 on 2018-10-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181007_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsubjects',
            name='owner',
        ),
        migrations.AlterField(
            model_name='staffsubjects',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
