# Generated by Django 2.0.7 on 2018-10-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20181015_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEM', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1)),
                ('USN_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffId', models.IntegerField()),
                ('staff_name', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='staffSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='owner',
        ),
        migrations.AddField(
            model_name='staffsubjects',
            name='Subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subjects'),
        ),
        migrations.AddField(
            model_name='staffsubjects',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
