# Generated by Django 2.0.7 on 2018-10-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181015_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classstudents',
            name='USN_1',
        ),
        migrations.DeleteModel(
            name='ClassStudents',
        ),
    ]
