# Generated by Django 2.0.7 on 2018-10-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181015_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEM', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1)),
                ('USN_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Staff Assignment'},
        ),
    ]
